config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'welcome#home'
  get 'about', to:'welcome#about'
  get 'signup', to:'users#new'
  resources :users, except: [:new]
   resources :articles do
     resources :comments
   end
   get 'login', to: 'sessions#new'
   post 'login', to: 'sessions#create'
   delete 'logout', to: 'sessions#destroy'
   resources :categories
 end

app/models/user.rb
class User < ApplicationRecord
    has_many :articles, dependent: :destroy

    before_save {self.email = email.downcase}
    validates :username, presence: true, 
              length: {minimum: 3, maximum: 25}, 
              uniqueness: {case_sensitive: false}
    validates :email, presence: true ,
              length: { maximum: 103 },
              uniqueness: {case_sensitive: false},
              format: { with: /[a-z0-9]+@[a-z]+\.[a-z]{2,3}/i , message: "Not a valid email address"}
    has_secure_password
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :set_user, only: [:edit, :update, :show, :destroy ]
    before_action :require_login, only: [:edit, :update, :show ] 
    before_action :require_user, except: [:new , :create, :destroy]
    before_action :require_same_user, only: [:edit, :update, :destroy]
    before_action :require_admin, only: [:destroy]
    def index 
        @user = User.paginate(page: params[:page], :per_page => 5)
    end

    def new
        @user = User.new
    end

    def show 
        @user_articles = @user.articles.paginate(page: params[:page], :per_page => 1 )
    end

    def create 
        @user = User.new(user_params)
       
        if @user.save
            session[:user_id] = @user.id
            redirect_to user_path(@user)
        else
            render 'new' , status: :unprocessable_entity
        end
    end

    def edit 
    end

    def update
       
        if @user.update(user_params)
            redirect_to @user
        else
            render 'edit', status: unprocessable_entity
        end
    end
    
    def destroy
        if current_user == @user
            current_user.destroy
            session.clear
            redirect_to root_path
            flash[:notice] = "Your account has been deleted successfully!"
        else
            @user.destroy
            redirecrt_to users_path, status: :see_other
        end
    end

    private
    def user_params
     params.require(:user).permit(:username, :email, :password)
    end

    def set_user
        if User.exists?(params[:id])
          @user = User.find(params[:id])
        else
            flash[:error] = "You must be logged in"
            redirect_to login_path
        end
    end

    def require_same_user 
        if current_user != @user and !current_user.admin?
            flash[:error] = "Not authorized!"
            redirect_to users_path
        end
    end

    def require_admin
        current_user.admin?
    end
end

app/helpers/users_helper.rb
module UsersHelper
    def gravatar_for(user , options = {size:80 })
        gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
        size= options[:size]
        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
        image_tag(gravatar_url,alt:user.username,class:"img-circle")
    end
end

app/views/users/_form.html.erb
<%= form_with model: user do |form| %>
  <div>
    <%= form.label :username %><br>
    <%= form.text_field :username %>
    <% user.errors.full_messages_for(:username).each do |message| %>
     <div> <%= message%> </div>
    <% end %>
  </div>

  <div>
    <%= form.label :email %><br>
    <%= form.text_field :email %><br>
    <% puts user.errors.full_messages%> 
    <% user.errors.full_messages_for(:email).each do |message|%>
     <div> <%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :password %><br>
    <%= form.password_field :password %><br>
    <% user.errors.full_messages_for(:password).each do |message|%>
     <div> <%= message%> </div>
    <% end %>
  </div>

  <div>
    <%= form.submit (@user.new_record? ? "Sign up" : "Update account")%>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1> Edit User </h1>

<%= render "form", user: @user%>
<%= link_to "Back", user_path%>

app/views/users/index.html.erb
<h1>Users</h1>

<%  if @user.length()==0 %>
   No Users
   <% else %>
   <ul>
  <% @user.each do |u| %>
    <li>
     <%= link_to u.username, u%>
     <small>Created : 
      <%= time_ago_in_words(u.created_at)%> ago,
      last updted: <%= time_ago_in_words(u.updated_at)%> ago
     </small></br>
    <small> <strong> <%= pluralize(u.articles.count , "article") if u.articles %> </strong> </small>
    </li>
  <% end%>
</ul>
<% end %></br>
<%= will_paginate @user%>
<%= link_to "Create New User", signup_path%>

app/views/users/new.html.erb
<h1>Sign up for alpha blog </h1>

<%= render "form", user: @user %>

app/views/users/show.html.erb
 <h1> <%= @user.admin? ? "Admin" : "User"%> information</h1>
<%= gravatar_for @user %>
<div> 
  <strong> Username : </strong>
  <%= @user.username%>
</div>
<div>
 <strong> Email : </strong>
 <%= @user.email%>
</div>

<% if @user.articles.size > 0 %>
<h4> <%=@user.username%>'s Articles </h4>
<% end %>

<%=render 'articles/article', obj:@user_articles%>
<%= will_paginate @user_articles%></br>

<%= link_to 'Back', users_path%>
<% if logged_in? && (current_user == @user || current_user.admin? ) %>

<%= link_to 'Edit', edit_user_path%>
<%= link_to 'Delete', user_path(@user) , data: {
  turbo_method: :delete,
  turbo_confirm: 'Are you sure?'
}%> 
<% end %>